<?php
/**
 * DeepSID / Account Class
 *
 * Validates and maintains users via registrations, login, logout and more. It
 * uses a designated user table in the database. It started as 'FGMemberSite',
 * was modified for GameDeed.com, and then simplified for DeepSID.
 *
 * The original HTML Form Guide v1.0 was published under the terms of the GNU
 * Lesser General Public License: http://www.gnu.org/copyleft/lesser.html
 *
 * @see http://www.html-form-guide.com/php-form/php-registration-form.html
 * @see http://www.html-form-guide.com/php-form/php-login-form.html
 *
 * When a login is successful, the following session variables are available:
 *
 *		$_SESSION['user_name']			user name
 *		$_SESSION['user_id']			user ID
 *		$_SESSION['roles']     			role(s)
 *
 *		$_SESSION['user_XXXXXXXXXX']	user name (for login check)
 *
 * The "random" 'user_XXXXXXXXXX' is generated by $this->loginSession().
 *
 * @copyright 2013-2026 Jens-Christian Huus
 */

require_once("setup.php");

$account = new Account();

class Account {

	/**
	 * @link	http://tinyurl.com/randstr
	 */
	private $rand_key			= 'l9iWfvkvzxBIyKK';

	private $database;
	private $error_message;

	/**
	 * Connects to the database using PDO. Call this before any database operation.
	 * 
	 * Made public in November 2025.
	 *
	 * @return		boolean		false = call $this->getErrorMessage()
	 */
	public function connectDB() {

		global $config; // Defined in 'setup.php'

		try {
			// Skip connecting if already connected
			if ($this->database instanceof PDO) {
				return true;
			}

			$options = array(
				PDO::MYSQL_ATTR_FOUND_ROWS	=> true, // So that UPDATE statements actually return a row
				PDO::ATTR_ERRMODE			=> PDO::ERRMODE_EXCEPTION
			);
			$this->database = new PDO(
				'mysql:host='.$config['db_deepsid_host'].';dbname='.$config['db_deepsid_name'],
				$config['db_deepsid_user'],
				$config['db_deepsid_pwd'],
				$options);
			$this->database->exec("SET NAMES utf8mb4");
			return true;

		} catch (PDOException $exception) {
			$this->logError($exception->getMessage());
			return false;
		}
	}

	/**
	 * Returns the PDO database connection.
	 * 
	 * @return		PDO			The PDO database connection
	 */
	public function getDB() {
		if (!$this->connectDB())
			throw new RuntimeException("Failed to connect to database.");

		return $this->database;
	}

	/**
	 * Registers a new user.
	 *
	 * @uses		$_POST['submitted'] - set when registration form is submitted
	 * @uses		$_POST[$this->spamTrapName()] - hidden input field
	 *
	 * @return		boolean		false = call $this->getErrorMessage()
	 */
	public function registerUser() {
		if (!isset($_POST['submitted'])) return false;

		// This is a hidden input field (humans won't fill this field)
		if (!empty($_POST[$this->spamTrapName()])) {
			// The error message is deliberately vague
			$this->handleError('A database error occurred; please try again later');
			return false;
		}

		if (!$this->connectDB()) return false;

		if (!$this->isFieldUnique('username')) {
			$this->handleError('This user name has already been taken');
			return false;
		}        

		if (!$this->createUser()) {
			$this->handleError('Could not create the user in the database');
			return false;
		}

		$this->logActivity('User "'.$_POST['username'].'" has registered for the site');
		return true;
	}

	/**
	 * Login an existing user.
	 *
	 * @uses		$_POST['username']
	 * @uses		$_POST['password']
	 *
	 * @return		boolean		false = call $this->getErrorMessage()
	 */
	public function login() {
		$user_name = trim($_POST['username']);
		$password = trim($_POST['password']);

		if (!isset($_SESSION)) session_start();
		if (!$this->validateLogin($user_name, $password)) {
			$this->logActivity('User "'.$user_name.'" tried to log in but was denied access');
			return false;
		}

		$_SESSION[$this->loginSession()] = $user_name;

		// Remember
		$cookiehash = md5(sha1($_SESSION['user_name'].$_SERVER['REMOTE_ADDR']));
		setcookie('user', $cookiehash, time()+3600*24*365, '/', COOKIE_HOST);

		try {
			// Store the hash in the database
			$update = $this->database->prepare('UPDATE users SET session = :cookiehash WHERE user_name = :user_name LIMIT 1');
			$update->execute(array(':cookiehash' => $cookiehash,':user_name' => $user_name));
			if ($update->rowCount() == 0)
				return false;
		} catch(PDOException $exception) {
			$this->logError($exception->getMessage());
			return false;
		}

		$this->logActivity('User "'.$user_name.'" logged in');
		return true;
	}

	/**
	 * Checks if a user is logged in at all.
	 *
	 * @return		boolean		false if user is not logged in
	 */
	public function checkLogin() {
		if (!isset($_SESSION)) session_start();

		if (empty($_SESSION[$this->loginSession()]) && !$this->checkCookieLogin()) return false;

		return true;
	}

	/**
	 * Returns the user name of the logged in user.
	 *
	 * @return		string		user name, or empty if not logged in
	 */
	public function userName() {
		return isset($_SESSION['user_name']) ? $_SESSION['user_name'] : '';
	}

	/**
	 * Returns the user ID of the logged in user.
	 *
	 * @return		string		user ID, or empty if not logged in
	 */
	public function userID() {
		return isset($_SESSION['user_id']) ? $_SESSION['user_id'] : '';
	}

	/**
	 * Checks if a user name is already taken.
	 *
	 * @return		boolean		false if the user name is taken
	 */
	public function isUserNameUnique() {
		if (!$this->connectDB()) return false;
		return $this->isFieldUnique('username');
	}

	/**
	 * Check if the user has the specified role.
	 * 
	 * @param		string		role
	 * 
	 * @return		boolean		true if the user has that role
	 */
	public function hasRole($role) {
		if (!isset($_SESSION)) session_start();
		$roles = $_SESSION['roles'] ?? [];
		return in_array($role, $roles, true);
	}

	/**
	 * Check if the user is an admin.
	 * 
	 * @return		boolean		true if the user is an admin
	 */
	public function isAdmin() {
		return $this->hasRole('admin');
	}

	/**
	 * Logout.
	 */
	public function logOut() {
		session_start();
		$this->logActivity('User "'.$_SESSION['user_name'].'" logged out');

		$session = $this->loginSession();
		$_SESSION[$session] = null;
		unset($_SESSION[$session]);

		setcookie('user', '', time()-3600, '/', COOKIE_HOST);
	}

	/**
	 * Changes the password (settings).
	 *
	 * @uses		$_POST['oldpwd']
	 * @uses		$_POST['newpwd']
	 *
	 * @return		boolean		false = call $this->getErrorMessage()
	 */
	public function changePassword() {
		// NOTE: This error should never occur (the settings will not be shown if not logged in).
		if (!$this->checkLogin()) {
			$this->handleError('User is not logged in');
			return false;
		}

		if (empty($_POST['oldpwd'])) {
			$this->handleError('The old password is empty');
			return false;
		}
		if (empty($_POST['newpwd'])) {
			$this->handleError('The new password is empty');
			return false;
		}

		// Find the user by user name in the database and fill an array
		$profile = array();
		if (!$this->getProfile($this->userName(), $profile)) return false;

		if ($profile->password != md5(trim($_POST['oldpwd']))) {
			$this->handleError('The old password does not match');
			return false;
		}
		// Store the password in the database
		if (!$this->storePassword($profile, trim($_POST['newpwd']))) return false;
		$this->logActivity('User "'.$_SESSION['user_name'].'" changed the password');
	
		return true;
	}

	/**
	 * Writes a line to an activity log file describing an activity.
	 * 
	 * NOTE: This is used for debugging purposes. Ratings set by users for specific
	 * SID files are never logged as this is none of my business. However, the names
	 * of playlists being created, renamed, deleted or published will be logged.
	 * 
	 * @param		string		text to be logged
	 * @param		boolean		true if common (will have a weaker color)
	 */
	public function logActivity($str, $common = false) {
		static $rotatedThisRequest = false;

		// Run rotation opportunistically on the 1st of each month
		if (!$rotatedThisRequest && (int)date('j') === 1) {
			@require_once __DIR__ . '/rotate_logs.php';
			$rotatedThisRequest = true;
		}

		$time_ip = date('Y-m-d H:i:s', strtotime(TIME_ADJUST)).' - '.$_SERVER['REMOTE_ADDR'].' - ';
		file_put_contents($_SERVER['DOCUMENT_ROOT'].'/deepsid/logs/activity.txt', ($common ? '<span style="color:#999;">' : '').$time_ip.$str.($common ? '</span>' : '').PHP_EOL, FILE_APPEND);
	}

	/**
	 * Writes a line to an activity log file describing an error.
	 * 
	 * @param		string		name of script
	 * @param		string		text to be logged
	 */
	public function logActivityError($script, $str) {
		$str = str_replace('You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use', 'Error in SQL syntax;', $str);
		$this->logActivity('<span style="color:#c00;font-weight:bold;">***** '.$script.' ***** '.$str.'</span>');
	}

	/**
	 * Returns the value of a setting in the administrator settings table.
	 * 
	 * @param		string			name of setting, e.g. "search_limit"
	 * 
	 * @return		string|null		the value, or null if not found
	 */
	public function getAdminSetting($key) {
		static $cache = [];

		// If we've seen this key before, return cached value
		if (array_key_exists($key, $cache)) {
			return $cache[$key];
		}

		if (!$this->connectDB()) return null;

		try {
			$select = $this->database->prepare(
				'SELECT setting_value FROM admin_settings WHERE setting_key = :key LIMIT 1'
			);
			$select->execute([':key' => $key]);
			$row = $select->fetch(PDO::FETCH_OBJ);
			$value = $row ? $row->setting_value : null;

			$cache[$key] = $value;
			return $value;

		} catch (PDOException $exception) {
			$this->logError($exception->getMessage());
			return null;
		}
	}

	/**
	 * Returns all settings in the administrator settings table.
	 * 
	 * @return	    array		array with keys and values
	 */
	public function getAllAdminSettings() {
		if (!$this->connectDB()) return null;
		try {
			$settings = [];
			$select = $this->database->query('SELECT setting_key, setting_value FROM admin_settings');
			while ($row = $select->fetch(PDO::FETCH_ASSOC)) {
				$settings[$row['setting_key']] = $row['setting_value'];
			}
			return $settings;

		} catch(PDOException $exception) {
			$this->logError($exception->getMessage());
			return null;
		}
	}

	/**
	 * @return		string		name of the current script
	 */
	public function self() {
		return htmlentities($_SERVER['PHP_SELF']);
	}    

	/**
	 * @uses		$_POST[$value]
	 */
	public function postValue($value) {
		if (empty($_POST[$value])) return '';
		return htmlentities($_POST[$value]);
	}

	/**
	 * Careful with this command, any HTML code before it and it won't redirect.
	 */
	public function redirect($url) {
		header('Location: '.$url);
		exit;
	}

	/**
	 */
	public function spamTrapName() {
		return 'sp'.md5('KHGdnbvsgst'.$this->rand_key);
	}

	/**
	 * Returns an error message if one is stored by handleError().
	 */
	public function getErrorMessage() {
		return $this->error_message;
	}    

	// --------------------------------------------------------------------------
	// PRIVATE FUNCTIONS
	// --------------------------------------------------------------------------

	/**
	 * Stores an error message to be retrieved by getErrorMessage().
	 *
	 * @param		string		error message
	 */
	private function handleError($message) {
		$this->error_message = $message;
	}

	/**
	 * Stores database error message for use by a call to getErrorMessage(). Also logs
	 * the elaborate PDO error to a file for inspection by an administrator.
	 *
	 * @param		string		reason for the error (for the log only)
	 * @param		[string]	public error message (default message is common/vague)
	 */
	private function logError($reason, $message = 'A database error occurred; please try again later') {
		$this->handleError($message);
		$path = $_SERVER['DOCUMENT_ROOT'];
		// Time and IP address is first in log entry
		$time_and_ip = date('Y-m-d H:i:s', strtotime(TIME_ADJUST)).' - '.$_SERVER['REMOTE_ADDR'].' - ';
		// We need to know the line number and the name of the function that generated this error
		$callers = debug_backtrace();
		// The detailed error is logged to a file on the web server
		file_put_contents($path.'/deepsid/logs/db_errors_account.txt', $time_and_ip.'Line '.$callers[0]['line'].' in '.$callers[1]['function'].'(): "'.$message.'"'.PHP_EOL.
			'Reason: '.$reason.PHP_EOL.PHP_EOL, FILE_APPEND);
	}

	/**
	 * Used by $_SESSION['user_XXXXXXXXXX'] as a login flag.
	 *
	 * @return		string		user_XXXXXXXXXX
	 */
	private function loginSession() {
		return 'user_'.substr(md5($this->rand_key), 0, 10);
	}

	/**
	 * Checks that the user name and password is correct. After 5 failed login attempts, temporary banning
	 * is activated for 10 minutes.
	 *
	 * @param		string		user name
	 * @param		string		password
	 *
	 * @return		boolean		false = call $this->getErrorMessage()
	 */
    private function validateLogin($user_name, $password) {
		if (!$this->connectDB()) return false;

		try {
			$select = $this->database->prepare('SELECT id, user_name, attempts, last_failed_login'.
				' FROM users WHERE user_name = :user_name AND password = :pwdmd5 LIMIT 1');
			$select->execute(array(':user_name' => $user_name, ':pwdmd5' => md5($password)));
			$select->setFetchMode(PDO::FETCH_OBJ);
			if ($select->rowCount() == 0) {
				// No results - try again without password to see if the user exists at all
				$select = $this->database->prepare('SELECT user_name, attempts FROM users WHERE user_name = :user_name LIMIT 1');
				$select->execute(array(':user_name' => $user_name));
				$select->setFetchMode(PDO::FETCH_OBJ);
				if ($select->rowCount() == 0) {
					$this->handleError('Error logging in; the user name does not exist');
					return false;
				} else {
					// So the user is there, the password was just wrong
					$row = $select->fetch();
					$attempts = $row->attempts + 1;

					$update = $this->database->prepare('UPDATE users SET attempts = :attempts WHERE user_name = :user_name LIMIT 1');
					$update->execute(array(':attempts' => $attempts, ':user_name' => $user_name));
					if ($update->rowCount() == 0) {
						$this->logError('No rows found after increasing login attempts for the user "'.$user_name.'"');
						return false;
					}

					if ($attempts > 5) {
						// Reached 5 attempts or more, so set a time stamp in the database
						// NOTE: Additional attempts after 5 will just update this time and thus reset the 10 minutes continuously.
						$logintime = date('Y-m-d H:i:s', strtotime(TIME_ADJUST));
						// Storing the IP address of the failed attempt is strictly for internal informational purposes. If the
						// same IP is seen for a ton of users, it could be a hacker and you would want to ban the IP address.
						$failip = $_SERVER['REMOTE_ADDR'];
						$update = $this->database->prepare('UPDATE users SET last_failed_login = :logintime, last_failed_ip = :failip'.
							' WHERE user_name = :user_name LIMIT 1');
						$update->execute(array(':logintime' => $logintime, ':failip' => $failip, ':user_name' => $user_name));
						if ($update->rowCount() == 0) {
							$this->logError('No rows found after updating login time and failed IP address '.$failip.' for the user "'.$user_name.'"');
							return false;
						}
						$this->handleError("You have been temporarily banned for 10 minutes");
					} else {
						$this->handleError('The password is incorrect');
					}
					return false;
				}
			} else {
				// The user and password is correct
				$row = $select->fetch();

				$minutes = round((strtotime(date('Y-m-d H:i:s', strtotime(TIME_ADJUST))) - strtotime($row->logintime)) / 60);
				if ($row->attempts >= 5 && $minutes < 10) {
					$this->handleError('You are still banned for another '.(10 - $minutes).' minutes');
					return false;
				}

				// Store login time and also make sure attempts are back to 0
				$update = $this->database->prepare('UPDATE users SET last_visit = NOW(), attempts = 0 WHERE user_name = :user_name LIMIT 1');
				$update->execute(array(':user_name' => $user_name));
				if ($update->rowCount() == 0) {
					$this->logError('No rows found after resetting login attempts for the user "'.$user_name.'"');
					return false;
				}

				$_SESSION['user_name']	= $row->user_name;
				$_SESSION['user_id']	= $row->id;
				$_SESSION['roles']		= $this->getUserRoles($row->id);

				return true;
			}
		} catch(PDOException $exception) {
			$this->logError($exception->getMessage());
			return false;
		}
    }

	/**
	 * Checks to see if user is remembered via a cookie.
	 *
	 * Only called by checkLogin().
	 *
	 * @return		boolean		false if not remembering login (or database error)
	 */
	private function checkCookieLogin() {
		if (isset($_COOKIE['user'])) {
			$cookiehash = $_COOKIE['user'];

			if (!empty($cookiehash)) {
				if (!$this->connectDB()) return false;
				try {
					$select = $this->database->prepare('SELECT id, user_name FROM users WHERE session = :cookiehash LIMIT 1');
					$select->execute(array(':cookiehash'=>$cookiehash));
					$select->setFetchMode(PDO::FETCH_OBJ);
					if ($select->rowCount() > 0) {
						$row = $select->fetch();
						$_SESSION['user_name']	= $row->user_name;
						$_SESSION['user_id']	= $row->id;
						$_SESSION['roles']		= $this->getUserRoles($row->id);
						$_SESSION[$this->loginSession()] = $row->user_name;

						$this->logActivity('User "'.$row->user_name.'" has returned via a cookie', true);

						// Reset the expiry date
						setcookie('user', $cookiehash, time()+3600*24*365, '/', COOKIE_HOST);

						// Store cookie login time
						$update = $this->database->prepare('UPDATE users SET last_visit = NOW() WHERE id = :id LIMIT 1');
						$update->execute(array(':id' => $row->id));
						return true;
					} else {
						// Commented out because it was blowing up the 'db_errors_account.txt' file
						// $this->logError('No rows found containing the cookie hash "'.$cookiehash.'"');
						return false;
					}
				} catch(PDOException $exception) {
					$this->logError($exception->getMessage());
					return false;
				}
			}
		}
		return false;
	}

	/**
	 * Stores the password in the database.
	 *
	 * @param		array		user information
	 * @param		string		the new password
	 *
	 * @return		boolean		false = call $this->getErrorMessage()
	 */
	private function storePassword($profile, $newpwd) {
		try {
			$update = $this->database->prepare('UPDATE users SET password = :password WHERE id = :user_id LIMIT 1');
			$update->execute(array(':password'=>md5($newpwd),':user_id'=>$profile->id));
			if ($update->rowCount() == 0) {
				$this->logError('No rows found after updating the password for the user "'.$profile->user_name.'"');
				return false;
			}
		} catch(PDOException $exception) {
			$this->logError($exception->getMessage());
			return false;
		}
		return true;
	}

	/**
	 * Returns an array with the user roles for the specified user ID.
	 * 
	 * @param		string		user ID
	 * 
	 * @return		array		user roles
	 */
	private function getUserRoles($userId) {
		if (!$this->connectDB()) return [];

		try {
			$select = $this->database->prepare('
				SELECT r.name
				FROM user_roles ur
				INNER JOIN roles r ON r.id = ur.role_id
				WHERE ur.user_id = :uid
			');
			$select->execute([':uid' => $userId]);
			return $select->fetchAll(PDO::FETCH_COLUMN, 0); // E.g. ['admin']
		} catch (PDOException $exception) {
			$this->logError($exception->getMessage());
			return [];
		}
	}

	/**
	 * Finds the user by user name and fills a profile array.
	 *
	 * @param		string		user name
	 * @param		array		user information (referenced array to be filled)
	 *
	 * @return		boolean		false = call $this->getErrorMessage()
	 */
	private function getProfile($user_name, &$profile) {
		if (!$this->connectDB()) return false;

		try {
			$select = $this->database->prepare('SELECT * FROM users WHERE user_name = :user_name LIMIT 1');
			$select->execute(array(':user_name' => $user_name));
			$select->setFetchMode(PDO::FETCH_OBJ);
			if ($select->rowCount() == 0) {
				$this->handleError('No user is registered with this user name: '.$user_name);
				return false;
			}
			$profile = $select->fetch(); // Fill user information array
		} catch(PDOException $exception) {
			$this->logError($exception->getMessage());
			return false;
		}
		return true;
	}

	/**
	 * Returns the absolute URL to the web site including the 'http[s]://' part.
	 *
	 * @return		string		when online it's 'https://deepsid.chordian.net'
	 */
	private function siteURL() {
		return (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' ? 'https://' : 'http://').$_SERVER['HTTP_HOST'];
	}

	/**
	 * Checks if a field is unique in the database table.
	 *
	 * @param		string		field name
	 *
	 * @return		boolean		false if the field is already there
	 */
	private function isFieldUnique($field) {
		try {
			$select = $this->database->prepare('SELECT user_name FROM users WHERE '.$field.'=:postfield');
			$select->execute(array(':postfield'=>$_POST[$field]));
			if ($select->rowCount() > 0) return false;
		} catch(PDOException $exception) {
			$this->logError($exception->getMessage());
			return false;
		}
		return true;
	}

	/**
	 * Adds a new user by inserting the $_POST variables in a new row.
	 *
	 * @return		boolean		false = call $this->getErrorMessage()
	 */
	private function createUser() {
		try {
			$insert = $this->database->prepare('INSERT INTO users(
				user_name,
				password,
				joined,
				session,
				attempts,
				last_failed_login,
				last_failed_ip
				) VALUES (
				:user_name,
				:password,
				CURDATE(),
				"",
				"0",
				:logintime,
				"0.0.0.0"
				)');
			$insert->execute(array(
				':user_name'	=> $_POST['username'],
				':password'		=> md5($_POST['password']),
				':logintime'	=> date('Y-m-d H:i:s', strtotime(TIME_ADJUST))
				));
			if ($insert->rowCount() == 0) {
				$this->logError('No rows found after inserting a new table row for the user "'.$_POST['username'].'"');
				return false;
			}
		} catch(PDOException $exception) {
			$this->logError($exception->getMessage());
			return false;
		}
		return true;
	}
}
?>